version: '2'

#https://docs.docker.com/compose/compose-file/#volumes-for-services-swarms-and-stack-files
#In the absence of having named volumes with specified sources, Docker creates an anonymous volume for each task backing a service. Anonymous volumes do not persist after the associated containers are removed.
volumes:
  volume-ab-postgres-compose:

services:
  postgres-db:
    image: postgres:9.6.9-alpine
    restart: always
    container_name: ab-postgres-docker-compose
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - PGDATA=/var/lib/postgresql/data/pgdata
      #- DB_USER=
      #- DB_PASS=
      #- DB_NAME=
      #- DB_TEMPLATE=
    volumes: 
      - volume-ab-postgres-compose:/var/lib/postgresql/data/pgdata