version: '3.7'
services:
  web:
    image: 'gitlab/gitlab-ce:16.3.6-ce.0'
    deploy:
      restart_policy:
        condition: any
    hostname: 'gitlab.homelab'
    secrets:
      - gitlab_db_password
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.homelab'
        postgresql['enable'] = true
        gitlab_rails['db_username'] = "gitlabuser"
        gitlab_rails['db_password'] = File.read('/run/secrets/gitlab_db_password').strip
        gitlab_rails['db_host'] = "postgres"
        gitlab_rails['db_database'] = "gitlab_production"
        gitlab_rails['db_port'] = 5432
    ports:
      - '81:80'
      - '444:443'
      - '23:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    networks:
      - gitlab_network

  postgres:
    image: postgres:13
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
    secrets:
      - gitlab_db_password
    environment:
      POSTGRES_USER: gitlabuser
      POSTGRES_PASSWORD_FILE: /run/secrets/gitlab_db_password
      POSTGRES_DB: gitlab_production
    volumes:
      - 'gitlab_postgres_data:/var/lib/postgresql/data'
    networks:
      - gitlab_network

  backup:
    image: 'gitlab/gitlab-ce:16.3.6-ce.0'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    command: >
      /bin/bash -c "
        while true; do
          echo \"executing backup command...\";
          gitlab-ctl reconfigure;
          echo \"reconfigure complete. Invoking gitlab-rake...\";
          gitlab-rake gitlab:backup:create;
          ls -la /var/opt/gitlab/backups/;
          mv /var/opt/gitlab/backups/* /backup;
          echo \"sleeping...\";
          sleep 86400;
        done
      "
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
      - 'nfs_backup:/backup'

networks:
  gitlab_network:
    driver: overlay

volumes: 
  gitlab_config: 
    labels:
      andrews-homelab: ""
  gitlab_logs: {}    
  gitlab_data: 
    labels:
      andrews-homelab: ""
  gitlab_postgres_data: 
    labels:
      andrews-homelab: ""
  nfs_backup:
    driver_opts:
      type: none
      device: /home/warden/homelab_nfs/arkham/gitlab_backups
      o: bind

secrets:
  gitlab_db_password:
    external: true