version: '3.7'
services:
  web:
    image: 'gitlab/gitlab-ce:16.3.6-ce.0'
    deploy:
      restart_policy:
        condition: any
    hostname: 'gitlab.homelab'
    secrets:
      - gitlab_db_password
      - homelab_nas_ip
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.homelab'
        postgresql['enable'] = true
        gitlab_rails['db_username'] = "gitlabuser"
        gitlab_rails['db_password'] = File.read('/run/secrets/gitlab_db_password').strip
        gitlab_rails['db_host'] = "postgres"
        gitlab_rails['db_database'] = "gitlab_production"
        gitlab_rails['db_port'] = 5432
      # workaround since docker secret expansion is not supported in volume definitions
      NFS_OPTIONS: "-o addr={{DOCKER_SECRET:nas_homelab_ip}},rw"
    ports:
      - '81:80'
      - '444:443'
      - '23:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    networks:
      - gitlab_network

  postgres:
    image: postgres:13
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
    secrets:
      - gitlab_db_password
    environment:
      POSTGRES_USER: gitlabuser
      POSTGRES_PASSWORD_FILE: /run/secrets/gitlab_db_password
      POSTGRES_DB: gitlab_production
    volumes:
      - 'gitlab_postgres_data:/var/lib/postgresql/data'
    networks:
      - gitlab_network

  backup:
    image: alpine:3.18
    depends_on:
      - web
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nfs_backup:/backups
    command: >
      sh -c "apk update && apk add --no-cache bash docker && \
      docker exec -t $$(docker ps -qf name=web) gitlab-backup create && \
      docker cp $$(docker ps -qf name=web):/var/opt/gitlab/backups/$$(ls -t /var/opt/gitlab/backups/ | head -1) /backups"
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: overlay

volumes: 
  gitlab_config: 
    labels:
      andrews-homelab: ""
  gitlab_logs: {}    
  gitlab_data: 
    labels:
      andrews-homelab: ""
  gitlab_postgres_data: 
    labels:
      andrews-homelab: ""
  nfs_backup: 
    driver_opts:
      # driver: local
      type: nfs
      o: "${NFS_OPTIONS}"
      device: ":/home/warden/homelab_nfs/arkham/gitlab_backups"

secrets:
  gitlab_db_password:
    external: true
  homelab_nas_ip:
    external: true