apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/ab-nvme-ssd/k3s-data/actual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
