version: '2'

#https://docs.docker.com/compose/compose-file/#volumes-for-services-swarms-and-stack-files
#In the absence of having named volumes with specified sources, Docker creates an anonymous volume for each task backing a service. Anonymous volumes do not persist after the associated containers are removed.
volumes:
  volume-ab-teamcity-compose:

services:
    teamcity:
        image: jetbrains/teamcity-server:10.0.1
        volumes:
            - volume-ab-teamcity-compose:/data/teamcity_server/datadir
            - volume-ab-teamcity-compose:/opt/teamcity/logs
        ports:
            - 8111:8111
        container_name: teamcity-server
        restart: always    
             
    teamcity-agent:
        image: jetbrains/teamcity-agent:10.0.1
        volumes:
            - volume-ab-teamcity-compose:/data/teamcity_agent/conf
        environment:
            SERVER_URL: http://teamcity:8111
        container_name: teamcity-agent
        restart: always